

def fail500(request):
    raise Exception('IntentionalFail: This Was On Purpose')
